In [1]:
name = "Avni"
age = 22
monthly_charge = 799.50

print(name)
print(age)
print(monthly_charge)

Avni
22
799.5

In [3]:
customer = {
    "name" : "Avni",
    "age" : 22,
    "tenure" : 12,
    "monthly_charges" : 799,
    "churn" : "No"
}
print(customer)

{'name': 'Avni', 'age': 22, 'tenure': 12, 'monthly_charges': 799, 'churn': 'No'}

In [4]:
print("Name :", customer["name"])
print("Monthly Charges :", customer["monthly_charges"])
print("Churn :", customer["churn"])

Name : Avni
Monthly Charges : 799
Churn : No

In [5]:
customers = [
    {"name": "Avni", "age": 22, "churn": "No"},
    {"name": "Rahul", "age": 25, "churn": "Yes"},
    {"name": "Priya", "age": 30, "churn": "No"}
]
for customer in customers:
    print(customer["name"])

Avni
Rahul
Priya

In [7]:
for customer in customers:
    print(customer["name"], "-", customer["churn"])

Avni - No
Rahul - Yes
Priya - No

In [8]:
def calculate_total(monthly_charge, months):
    total = monthly_charge * months
    return total

result = calculate_total(799, 12)

print(result)

9588

In [9]:
churn_probability = 0.72

if churn_probability >= 0.5:
    print("Customer is likely to churn")
else:
    print("Customer is likely to stay")

Customer is likely to churn

In [10]:
churn_probability = 0.30

if churn_probability >= 0.5:
    print("Customer is likely to churn")
else:
    print("Customer is likely to stay")

Customer is likely to stay

In [11]:
import pandas as pd

In [12]:
import pandas as pd

data = {
    "Name": ["Avni", "Rahul", "Priya"],
    "Age": [22, 25, 30],
    "Tenure": [12, 5, 24],
    "MonthlyCharges": [799, 999, 599],
    "Churn": ["No", "Yes", "No"]
}

df = pd.DataFrame(data)

print(df)

    Name  Age  Tenure  MonthlyCharges Churn
0   Avni   22      12             799    No
1  Rahul   25       5             999   Yes
2  Priya   30      24             599    No

In [13]:
df

    Name  Age  Tenure  MonthlyCharges Churn
0   Avni   22      12             799    No
1  Rahul   25       5             999   Yes
2  Priya   30      24             599    No

In [14]:
df["Age"]

0    22
1    25
2    30
Name: Age, dtype: int64

In [15]:
df["Churn"]

0     No
1    Yes
2     No
Name: Churn, dtype: str

In [16]:
df.head

<bound method NDFrame.head of     Name  Age  Tenure  MonthlyCharges Churn
0   Avni   22      12             799    No
1  Rahul   25       5             999   Yes
2  Priya   30      24             599    No>

In [17]:
df.head()

    Name  Age  Tenure  MonthlyCharges Churn
0   Avni   22      12             799    No
1  Rahul   25       5             999   Yes
2  Priya   30      24             599    No

In [18]:
df.head(3)

    Name  Age  Tenure  MonthlyCharges Churn
0   Avni   22      12             799    No
1  Rahul   25       5             999   Yes
2  Priya   30      24             599    No

In [19]:
df.head(2)

    Name  Age  Tenure  MonthlyCharges Churn
0   Avni   22      12             799    No
1  Rahul   25       5             999   Yes

In [20]:
df.shape

(3, 5)

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            3 non-null      str
 1   Age             3 non-null      int64
 2   Tenure          3 non-null      int64
 3   MonthlyCharges  3 non-null      int64
 4   Churn           3 non-null      str
dtypes: int64(3), str(2)
memory usage: 252.0 bytes

In [22]:
df.describe()

             Age     Tenure  MonthlyCharges
count   3.000000   3.000000             3.0
mean   25.666667  13.666667           799.0
std     4.041452   9.609024           200.0
min    22.000000   5.000000           599.0
25%    23.500000   8.500000           699.0
50%    25.000000  12.000000           799.0
75%    27.500000  18.000000           899.0
max    30.000000  24.000000           999.0

In [23]:
df.isnull().sum()

Name              0
Age               0
Tenure            0
MonthlyCharges    0
Churn             0
dtype: int64

In [24]:
df.columns

Index(['Name', 'Age', 'Tenure', 'MonthlyCharges', 'Churn'], dtype='str')